### ISSUE TITLE
[订正]做保安

### ISSUE THREAD

**Issue by Guanchishan** [Nang-muoi-sing/cdo-corpus#12]
部分字眼待正。
- [x] https://github.com/MindongLab/cdo-corpus/blob/6b8e3f351112b6d97cb5953dd7593e46f97edd7c/video/Unknown.%20%E5%81%9A%E4%BF%9D%E5%AE%89%5Bcdo-hani%5D.srt#L43

- [x] https://github.com/MindongLab/cdo-corpus/blob/6b8e3f351112b6d97cb5953dd7593e46f97edd7c/video/Unknown.%20%E5%81%9A%E4%BF%9D%E5%AE%89%5Bcdo-hani%5D.srt#L95

- [x] https://github.com/MindongLab/cdo-corpus/blob/6b8e3f351112b6d97cb5953dd7593e46f97edd7c/video/Unknown.%20%E5%81%9A%E4%BF%9D%E5%AE%89%5Bcdo-hani%5D.srt#L99

- [x] https://github.com/MindongLab/cdo-corpus/blob/6b8e3f351112b6d97cb5953dd7593e46f97edd7c/video/Unknown.%20%E5%81%9A%E4%BF%9D%E5%AE%89%5Bcdo-hani%5D.srt#L123

- [x] https://github.com/MindongLab/cdo-corpus/blob/ab9e7b815c42d87662f1d5602fa7d89dfc49c43c/video/Unknown.%20%E5%81%9A%E4%BF%9D%E5%AE%89%5Bcdo-hani%5D.srt#L299

**Comment by Tseing** [comment]
- Line43：相拍 汝總款單條骨也儥中拍吓 
- Line95：/huang53 leing(lian)33 ngooung242/指固执愚蠢的人，或许记作“横连歞(?)”
- Line123：門牌號偌夥
- Line299：我儂都等遘歞去了吓

**Comment by Guanchishan** [comment]
L99應該是「無關係」（？）

其他[照改](https://github.com/MindongLab/cdo-corpus/issues/12#issuecomment-643706315)。

**Comment by Guanchishan** [comment]
没大问题，暂时关闭。有疑问可以随时开启issue。
