### ISSUE TITLE
into new format

### ISSUE THREAD

**Issue by Guanchishan** [Nang-muoi-sing/cdo-corpus#17]
Audio | Mindong | Mandarin Trans. | ISO 639-6 | Area | Sex | Age | Pronunciation Provider | Provider | Year | YYYY-MM-DD | HH:MM:SS (UTC+8) | Source | Copyright | Tag | Flashcard | Note | Property | Multi-sentences Num.
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
mnhu. hf万物@QQ. 總款乇ing55zeo55去. 2020-06-17.mp3 | 總款(這樣的) 乇(東西) ？？(太多)[ing55-zeo55] 去(了). |   | mnhu |   | 男 |   | hf万物@QQ | 关彳山 |   | 2020-06-17 |   |   |   |   |   |   | speak |  
mnhu. hf万物@QQ. 總款乇野価, 崩去. 2020-06-17.mp3 | 總款(這樣的) 乇(東西) 野(非常) 価(多), ？(太多)[bung55] 去(了)[o0]. |   | mnhu |   | 男 |   | hf万物@QQ | 关彳山 |   | 2020-06-17 |   |   |   |   |   |   | speak |  
mnhu. 子善. 我這邊是盡価老儂總款其腔. 2020-06-25.mp3 | 我 這邊[zi21-meing55] 是 盡価 老儂 總款 其 腔. |   | mnhu |   | 男 |   | 子善 | 关彳山 |   | 2020-06-25 |   |   |   |   |   |   | speak |  
mnhu. 子善. 比喻講, 比喻講世乇𡅏. 2020-06-25.mp3 | 比喻(比方) 講(說), 比喻 講 世乇(什麼) 𡅏(呢). |   | mnhu |   | 男 |   | 子善 | 关彳山 |   | 2020-06-25 |   |   |   |   |   |   | speak |  
mnhu. 子善. 但是後生囝就伓是總款講了. 2020-06-25.mp3 | 但是 後生囝 就 伓是 總款[zung24-uang33] 講[oung33] 了. |   | mnhu |   | 男 |   | 子善 | 关彳山 |   | 2020-06-25 |   |   |   |   |   |   | speak |  
fzho. 烟雨三山@QQ. 叮所. 2020-06-23.mp3 | 底所(哪裏)[ding24-neo33]. |   | fzho |   | 男 |   | 烟雨三山@QQ | 关彳山 |   | 2020-06-23 |   |   |   |   |   |   | speak |  
cgle. 所以暂时将你眼镜闭了起来@QQ. 正是, 正是蜀样. 2020-06-21.mp3 | 正是(沒錯), 正是(就是) 蜀(同) 樣. |   | cgle | 長樂文嶺 | 女 |   | 所以暂时将你眼睛闭了起来@QQ | 关彳山 |   | 2020-06-21 |   |   |   |   |   |   | speak |  
cgle. 所以暂时将你眼睛闭了起来@QQ. 我是諸娘囝. 2020-06-21.mp3 | 我[ngui33] 是[si21] 諸娘囝[zy53-neoyng33-iang33]. |   | cgle | 長樂文嶺 | 女 |   | 所以暂时将你眼睛闭了起来@QQ | 关彳山 |   | 2020-06-21 |   |   |   |   |   |   | speak |  
mnhu. hf万物@QQ. 聽講汝這月工資加三千, 頭管吓, 㑚加千把. 2020-06-22.mp3 | 聽 講 汝 這 月 工資 加 三千. 頭管[tau33-uang33] 吓, 㑚 加 千把. |   | mnhu |   | 男 |   | hf万物@QQ | 关彳山 |   | 2020-06-22 |   |   |   |   |   |   | speak |  
mnhu. hf万物@QQ. 頭管伊也有米八懸, 伊乍米七幾. 2020-06-22.mp3 | 頭管 伊 也 有 米八 懸, 伊 乍 米七 幾. |   | mnhu |   | 男 |   | hf万物@QQ | 关彳山 |   | 2020-06-22 |   |   |   |   |   |   | speak |

**Comment by Guanchishan** [comment]
finished

**Comment by ztl8702** [comment]
👍
