### ISSUE TITLE
Update text corpus format

### ISSUE THREAD

**Issue by Guanchishan** [Nang-muoi-sing/cdo-corpus#19]
本issue讨论如何为文本语料（包括短句、篇章）设计出一个合适的xml标记格式。

希望这个格式：

- 具备泛用性，不会和市面上主流的xml语料标记格式相去太远
- 响应本闽东语语料库的实际需要

格式升级一案的相关讨论与进度在本issue进行。

## 背景

本闽东语语料库的语料，曾经采用文本本位的思路，进行[线性标注](https://web.archive.org/web/20200819191750/https://github.com/MindongLab/cdo-corpus/wiki/Corpus-format-%E8%AA%9E%E6%96%99%E6%A0%BC%E5%BC%8F)。

文本本位，即以一句句标记好的文本为基本的语料单位，音频依附于文本语料记录。
https://github.com/MindongLab/cdo-corpus/blob/a02b9d45ae0b07e61e8375ea15f6be51bd06a474/sentences.tsv#L59
例如上条记录，可发现音频以登记音频文件名的形式，依附于这条记录的尾端。在榕典[寻求训练数据发展TTS功能](https://github.com/MindongLab/yngdieng/issues/272)的需求面前，该标记方式亦有信息粒度过粗的缺点。

本库甚至曾特意设计出一个“语篇字段”好显示特定语料的上下文关系，期望服务于篇章研究。
![image](https://user-images.githubusercontent.com/30859354/90681383-e64c8380-e295-11ea-9630-2bd7ae15d80e.png)
数字同一代表隶属于同一篇章（可以视这个数字为篇章ID），篇章内排列先后顺序由语料在表格内的上下顺序决定。然而这也并不是一个特别优雅的标记手段。比如，表格惨遭乱序，则篇章信息也会被打乱。

在2020年8月8日的榕典/输入法例会上，郑天镭提出设计一种新的基于xml的语料标记格式。本库语料也将随之重新划分为两大类：

- 音频本位
- 文本本位

音频本位，即一切语料标注围绕着音频文件展开、存储。

对于音频本位的语料，我们将摒弃原有的线性标注结构，采取一种新的分层标记结构。拟直接利用支援类似功能的标注软件，对音频进行各类分层标注。其大致思想是，不再把注、释词等各种标注与转写出来的文本一起挤在一行；而是声音一层，转写一层，注音一层，对应释义一层云云。

我们依赖[ELAN](https://archive.mpi.nl/tla/elan/)完成这项工作。并于当月19日完成了短句有声语料的[格式转换](https://github.com/MindongLab/cdo-corpus/issues/17)，发布了[v0.4-beta.1](https://github.com/MindongLab/cdo-corpus/releases/tag/v0.4-beta.1)。

我们还在研究视频语料[应当沿用原有的.srt格式存储标记资料，还是转换为ELAN的模式](https://github.com/MindongLab/cdo-corpus/issues/20)。

剩下的没有对应音频的语料仍然采取文本本位的线性标注，但是标注格式要升级以符合xml格式。而原有文本本位的标记格式如何升级，则属于本issue的议题。

**Comment by Guanchishan** [comment]
xml文件有待考虑的存取方案：
- XAIRA（[语料库语言学在线帖子](https://www.corpus4u.org/threads/9421/)）

**Comment by ztl8702** [comment]
“存取”指的是检索？

**Comment by ztl8702** [comment]
ANNIS (https://corpus-tools.org/annis/) 这个工具是我目前了解到比较成熟的语料库（检索工具），有不少大学在用。 主要是提供一些比较丰富的检索功能，比如找某个词的上下文。(@Guanchishan 我email了你一个关于ANNIS的ppt）

ANNIS 的姐妹工具 -- 语料标注工具Atomic  https://corpus-tools.org/atomic/ 也可以试试看。（对于工具不用过于纠结，继续用ELAN也行。格式都是可以转换的）

**Comment by ztl8702** [comment]
ANNIS demo：https://korpling.german.hu-berlin.de/annis3/

**Comment by Guanchishan** [comment]
> “存取”指的是检索？

检索、本地读取与管理这样的。

但我下了这工具还没弄清楚怎么用。

> 我email了你一个关于ANNIS的ppt

cool，对[讲故事](https://github.com/MindongLab/cdo-corpus/issues/21)也很有帮助。

> ANNIS 的姐妹工具 -- 语料标注工具Atomic

看了下他们说给Atomic搞了个升级版：https://hexatomic.github.io/ 这款新工具你有过了解无？

**Comment by Guanchishan** [comment]
主要是ELAN是以时间轴为单位的，所以纯文本语料不适合用ELAN搞。

> 看了下他们说给Atomic搞了个升级版：https://hexatomic.github.io/ 

语料标注工具Atomic的官网上已经没有下载链接了，所以只好下载了[Hexatomic Beta 0.4.2](https://github.com/hexatomic/hexatomic/releases/tag/v0.4.2)。然后打不开（Win 10），如图。尝试修改Java的Path也又报别的错。

![image](https://user-images.githubusercontent.com/30859354/91639937-c747b180-ea4c-11ea-868c-c8d6a14cc60d.png)

换了[v0.3](https://github.com/hexatomic/hexatomic/releases/tag/v0.3.0)也报错如上。

**Comment by Guanchishan** [comment]
@ztl8702 不知道你那边跑不跑得动Hexatomic Beta 0.4.2？

**Comment by ztl8702** [comment]
我在mac上可以打开
<img width="802" alt="Screen Shot 2020-08-31 at 1 25 30 am" src="https://user-images.githubusercontent.com/2714446/91665531-dd2aa480-eb28-11ea-8fe1-157b214629ce.png">

**Comment by ztl8702** [comment]
你这个问题似乎是Java版本问题：https://jingyan.baidu.com/article/ca41422f1d71601eae99ed85.html

**Comment by Guanchishan** [comment]
hexatomic更像是个生成语法研究软件（虽然他在官网声称自己学派与理论中立）。而本库有些语料具备平行语料的性质。hexatomic只能对词标注，无法对句标注，也没地方记录meta-data。
而且一旦有哪个下属的文件发生问题，他整个语料库就打不开，报java错误。如果没有进行适当的备份那基本就等于全盘毁了。
hexatomic似乎也没有内建搜索功能，或者他的搜索在搜中文时太过难用。

不打算去适应hexatomic了。这两天好好补了语料库语言学的课，觉得过早投资到某一个软件的专有的格式里，以后都有返工的危险。

我这两天在：
- [ ] 研究用XMLSpy编写XML Schema文档，若能成功就
- [ ] 写相应的教程在维基区
- [ ] 然后把/plaintext目录下的文本语料转为xml文件

本issue就可告完成。

**Comment by Guanchishan** [comment]
符合XML Schema的新[格式](https://github.com/MindongLab/cdo-corpus/wiki/Corpus-format-%E8%AA%9E%E6%96%99%E6%A0%BC%E5%BC%8F)已設計好。

現在進入舊格式（`.tsv`）向新格式（`.xml`）消極過渡（即除非必須，否則不主動更新存量語料的格式）的階段。

結案。
