### ISSUE TITLE
[听写汉字]"請□着□□□其前後" from 福州地铁2号线报站紫阳站

### ISSUE THREAD

**Issue by Guanchishan** [Nang-muoi-sing/cdo-corpus#22]
待听写句位置：https://github.com/MindongLab/cdo-corpus/commit/c52d0796d0b99c2cc0ac9629ac7a821128f241ca#diff-0fa35fd0d6ac64f35954f6920c386331R138

**Comment by Guanchishan** [comment]
請□着=請伓通着。後面還是沒聽出

**Comment by Tseing** [comment]
各位乘客，请伓通著车厢礼食乇。列车运行辰候，请抓紧扶手，伓通靠著车门，以防夹伤去。

**Comment by Guanchishan** [comment]
Thank you for your contribution!

Leo ***@***.***> 于2022年8月10日周三 13:15写道：
