### ISSUE TITLE
福州传统叫卖声及其录音

### ISSUE THREAD

**Issue by Guanchishan** [Nang-muoi-sing/cdo-corpus#24]
2019-05-18，@yjfvictor 提供了两句福州传统叫卖声

> 曱甴药, 红蚁药, XX药, XX药, 风油精

> 高壓鍋, 煤氣竈, 熱水器, 清理油煙機

@siuze 也提供了两句：

> 按無元寶灰賣去

> 茶箬, 寶圓

不过方才整理时发现音频损坏。需要找时间重新收集这类声音与文本，多多益善。

**Comment by yjfvictor** [comment]
> 废品收购啊！图书、报纸、呆铜、呆铁啊！可乐瓶收购，易拉罐收购啊！

> 元宝灰啊！有无元宝灰卖无啊？

**Comment by Guanchishan** [comment]
> 有无元宝灰卖无啊？

只是确认下，即便前面说“有无”了，后面还是可以再加“无”吗？我一直以为这种算口误，但如果不是，就太好了。

**Comment by yjfvictor** [comment]
> > 有无元宝灰卖无啊？
> 
> 只是确认下，即便前面说“有无”了，后面还是可以再加“无”吗？我一直以为这种算口误，但如果不是，就太好了。

应该不太正确，只是那些人确实都这么吆喝的。

**Comment by Guanchishan** [comment]
@yjfvictor 那 高壓鍋, 煤氣竈, 熱水器, 清理油煙機 这句，一般是用福州话讲，还是用福州式普通话讲呢？

**Comment by yjfvictor** [comment]
> @yjfvictor 那 高壓鍋, 煤氣竈, 熱水器, 清理油煙機 这句，一般是用福州话讲，还是用福州式普通话讲呢？

「洗衣机」说福州话，其他说普通话。

gāo yā guō, méi qì zhào, rè shuǐ qì, _xěh yī gī_, qīng lǐ yóu yān jī.
高压锅，煤气灶，热水器，_洗衣机_，清理油烟机。

**Comment by Guanchishan** [comment]
> gāo yā guō, méi qì zhào, rè shuǐ qì, xěh yī gī, qīng lǐ yóu yān jī. 高压锅，煤气灶，热水器，洗衣机，清理油烟机。

有意思，寶貴的資料。我生活的地域很難接觸到這種帶平話的叫聲。你有興趣提供對應的錄音，比如方便的時候自行唸段音發給我嗎？可以發Telegram。

**Comment by Guanchishan** [comment]
以上内容已收录。暂无其他需求，关闭本issue
