### ISSUE TITLE
社交媒体短视频

### ISSUE THREAD

**Issue by ztl8702** [Nang-muoi-sing/cdo-corpus#4]
社交媒体短视频在收录范畴么？ 如https://v.douyin.com/sNsX8f/

**Comment by Guanchishan** [comment]
當然在，我只怕未經授權，有點縮手縮腳而已。我私存了一些平話小視頻，也不日上傳之。

**Comment by ztl8702** [comment]
这样的话。不一定要用Github。我想一想其他的（内部协作）工具。

**Comment by Guanchishan** [comment]
谷歌网盘？

**Comment by Guanchishan** [comment]
![image](https://user-images.githubusercontent.com/30859354/74566479-d749e900-4f73-11ea-86c8-9be525dc2452.png)
我都卡落来了，尚未推上云端。

**Comment by Guanchishan** [comment]
对了，之前似乎在谷歌协作文档里，学长汝講愛挃有聲音其語料，看囇[Wiki Commons](https://commons.wikimedia.org/wiki/Category:Audio_files_in_Min_Dong_Chinese)？

**Comment by Guanchishan** [comment]
> 可以放Google Drive

Done.

> 视频的元数据等可以放在Git中

Done.

> Transcription/字幕

会使。

> 应该可以算作“合理使用”。

正是总款。

> 可以检索元数据、和按字幕检索。

那可能还要给各视频设下编号什么的方便定位与索引。目前[表格旁自动配了行号1234等](https://github.com/MindongLab/cdo-corpus/blob/master/video/info.tsv#L2)，且先从这个？

**Comment by ztl8702** [comment]
OK

On Wed, 19 Feb 2020 at 09:03, Davidzdh <notifications@github.com<mailto:notifications@github.com>> wrote:

可以放Google Drive

Done.

视频的元数据等可以放在Git中

Done.

Transcription/字幕

会使。

应该可以算作“合理使用”。

正是总款。

可以检索元数据、和按字幕检索。

那可能还要给各视频设下编号什么的方便定位与索引。目前(表格旁自动配了行号1234等)[https://github.com/MindongLab/cdo-corpus/blob/master/video/info.tsv#L2]，且先从这个？

**Comment by Guanchishan** [comment]
Closing for now. Feel free to reopen if you have further questions.
