### ISSUE TITLE
[订正]林依妹“鱟桸故驚湯煺脫”段

### ISSUE THREAD

**Issue by Guanchishan** [Nang-muoi-sing/cdo-corpus#6]
https://github.com/MindongLab/cdo-corpus/blob/master/video/%5Bcdo-hani%5D%E9%B1%9F%E6%A1%B8%E6%95%85%E9%A9%9A%E6%B9%AF%E7%85%BA%E8%84%AB%E7%AD%89
 

- 还没听写全文本与时间轴(Done)

- 也没有切割(打算先不做切割了，弄好时间轴即可)

**Comment by ztl8702** [comment]
looks good

**Comment by Guanchishan** [comment]
- [x] 进度：正在弄时间轴；听写了部分句子
----
- [x] 只剩部分词打了问号待考

https://github.com/MindongLab/cdo-corpus/blob/e58af2120131cba1042c4e41c2ead2f7a905b5ce/video/%E6%9E%97%E9%A2%96.%20%E9%B1%9F%E6%A1%B8%E6%95%85%E9%A9%9A%E6%B9%AF%E7%85%BA%E8%84%AB%E7%AD%89%5Bcdo-hani%5D.srt#L30

https://github.com/MindongLab/cdo-corpus/blob/e58af2120131cba1042c4e41c2ead2f7a905b5ce/video/%E6%9E%97%E9%A2%96.%20%E9%B1%9F%E6%A1%B8%E6%95%85%E9%A9%9A%E6%B9%AF%E7%85%BA%E8%84%AB%E7%AD%89%5Bcdo-hani%5D.srt#L34

https://github.com/MindongLab/cdo-corpus/blob/e58af2120131cba1042c4e41c2ead2f7a905b5ce/video/%E6%9E%97%E9%A2%96.%20%E9%B1%9F%E6%A1%B8%E6%95%85%E9%A9%9A%E6%B9%AF%E7%85%BA%E8%84%AB%E7%AD%89%5Bcdo-hani%5D.srt#L130

**Comment by Guanchishan** [comment]
fixed in https://github.com/MindongLab/cdo-corpus/commit/bf22571094207a14259d1d7529a2bb5f04d69c5c
